apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: publicdocs-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:henrik-nic/nicPublicdocs.git
    targetRevision: main
    path: deploy/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: local-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
