apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-dev

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: nicpublicdocs
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nicpublicdocs-dev.localtest.me

images:
  - name: k3d-local-registry:5000/nicpublicdocs
    newTag: dev
